// title page..
import { Metadata } from 'next';

export const metadata: Metadata = {
	title: 'Blog list',
	description: 'Generated by RYO IT',
};

// title of blogList
// Nhớ đi cùng layout.tsx và page.tsx => working
export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	// children án chỉ đến page.tsx
	return <>{children}</>;
}
