// import './globals.css'
'use client';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import 'bootstrap/dist/css/bootstrap.min.css';
import AppHeader from './../components/app.header';
import AppFooter from './../components/app.footer';
import Container from 'react-bootstrap/Container';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

// layout la trang root cho phep tai su dung nhieu lan ko can thay doi giao dieu
// khi chuyen huong route page

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<AppHeader />
				<Container>
					{children}
					<ToastContainer
						position='bottom-center'
						autoClose={5000}
						hideProgressBar={false}
						newestOnTop={false}
						closeOnClick
						rtl={false}
						pauseOnFocusLoss
						draggable
						pauseOnHover
						theme='light'
					/>
				</Container>
				<AppFooter />
			</body>
		</html>
	);
}
