// title page..
import { Metadata } from 'next';

export const metadata: Metadata = {
	title: 'View Detail Blog',
	description: 'Generated by RYO IT',
};

// title of blogList

export default function ViewDetaiLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	// children án chỉ đến page.tsx
	return <>{children}</>;
}
